INSERT INTO UTEndUse (name, data_type, number_allowed) VALUES ('value', 'fk_list_primitive_field', '?');
INSERT INTO UTEndUse (name, data_type, number_allowed) VALUES ('other', 'string_primitive_field', '?');
INSERT INTO UTEndUse_valueLookup (name, label) VALUES ('0', 'Food - human');
INSERT INTO UTEndUse_valueLookup (name, label) VALUES ('1', 'Food - animal');
INSERT INTO UTEndUse_valueLookup (name, label) VALUES ('2', 'Medicine - human & veterinary');
INSERT INTO UTEndUse_valueLookup (name, label) VALUES ('3', 'Poisons');
INSERT INTO UTEndUse_valueLookup (name, label) VALUES ('4', 'Manufacturing chemicals');
INSERT INTO UTEndUse_valueLookup (name, label) VALUES ('5', 'Other chemicals');
INSERT INTO UTEndUse_valueLookup (name, label) VALUES ('6', 'Fuels');
INSERT INTO UTEndUse_valueLookup (name, label) VALUES ('7', 'Fibre');
INSERT INTO UTEndUse_valueLookup (name, label) VALUES ('8', 'Construction or structural materials');
INSERT INTO UTEndUse_valueLookup (name, label) VALUES ('9', 'Wearing apparel, accessories');
INSERT INTO UTEndUse_valueLookup (name, label) VALUES ('10', 'Other household goods');
INSERT INTO UTEndUse_valueLookup (name, label) VALUES ('11', 'Handicrafts, jewellery, etc.');
INSERT INTO UTEndUse_valueLookup (name, label) VALUES ('12', 'Pets/display animals, horticulture');
INSERT INTO UTEndUse_valueLookup (name, label) VALUES ('13', 'Research');
INSERT INTO UTEndUse_valueLookup (name, label) VALUES ('14', 'Sport hunting/specimen collecting');
INSERT INTO UTEndUse_valueLookup (name, label) VALUES ('15', 'Establishing ex-situ production *');
INSERT INTO UTEndUse_valueLookup (name, label) VALUES ('16', 'Other (free text)');
INSERT INTO UTEndUse_valueLookup (name, label) VALUES ('17', 'Unknown');
INSERT INTO UTCaptiveHarvest (name, data_type, number_allowed) VALUES ('value', 'boolean_unknown_primitive_field', '?');
INSERT INTO UTHarvestTrendComments (name, data_type, number_allowed) VALUES ('narrative', 'text_primitive_field', '?');
INSERT INTO UTLocalLivelihood (name, data_type, number_allowed) VALUES ('subsistence', 'boolean_unknown_primitive_field', '?');
INSERT INTO UTLocalLivelihood (name, data_type, number_allowed) VALUES ('localcommercial', 'boolean_unknown_primitive_field', '?');
INSERT INTO UTLocalLivelihood (name, data_type, number_allowed) VALUES ('subsistenceRationale', 'text_primitive_field', '?');
INSERT INTO UTLocalLivelihood (name, data_type, number_allowed) VALUES ('localcommercialDetail', 'text_primitive_field', '?');
INSERT INTO UTNatlCommercialValue (name, data_type, number_allowed) VALUES ('value', 'boolean_unknown_primitive_field', '?');
INSERT INTO UTIntlCommercialValue (name, data_type, number_allowed) VALUES ('value', 'boolean_unknown_primitive_field', '?');
INSERT INTO UTGeneralNotes (name, data_type, number_allowed) VALUES ('value', 'text_primitive_field', '?');
INSERT INTO UTWildHarvestRecord (name, data_type, number_allowed) VALUES ('dateOfHarvest', 'date_primitive_field', '?');
INSERT INTO UTWildHarvestRecord (name, data_type, number_allowed) VALUES ('recordDate', 'string_primitive_field', '?');
INSERT INTO UTWildHarvestRecord (name, data_type, number_allowed) VALUES ('isTotalSpeciesRange', 'boolean_primitive_field', '?');
INSERT INTO UTWildHarvestRecord (name, data_type, number_allowed) VALUES ('percentGlobalRange', 'float_primitive_field', '?');
INSERT INTO UTWildHarvestRecord (name, data_type, number_allowed) VALUES ('otherGeographicScope', 'text_primitive_field', '?');
INSERT INTO UTWildHarvestRecord (name, data_type, number_allowed) VALUES ('source', 'fk_primitive_field', '?');
INSERT INTO UTWildHarvestRecord_sourceLookup (name, label) VALUES ('0', 'Wild');
INSERT INTO UTWildHarvestRecord_sourceLookup (name, label) VALUES ('1', 'Augmented/enriched population (e.g. salmon/eels restocking to wild)');
INSERT INTO UTWildHarvestRecord_sourceLookup (name, label) VALUES ('2', 'Unknown');
INSERT INTO UTWildHarvestRecord (name, data_type, number_allowed) VALUES ('formRemoved', 'fk_primitive_field', '?');
INSERT INTO UTWildHarvestRecord_formRemovedLookup (name, label) VALUES ('0', 'Whole animal plant (including eggs, fruit, seeds)');
INSERT INTO UTWildHarvestRecord_formRemovedLookup (name, label) VALUES ('1', 'Parts non-lethal removal');
INSERT INTO UTWildHarvestRecord_formRemovedLookup (name, label) VALUES ('2', 'Parts lethal removal');
INSERT INTO UTWildHarvestRecord_formRemovedLookup (name, label) VALUES ('3', 'Other');
INSERT INTO UTWildHarvestRecord (name, data_type, number_allowed) VALUES ('formRemovedOther', 'text_primitive_field', '?');
INSERT INTO UTWildHarvestRecord (name, data_type, number_allowed) VALUES ('lifeStageRemoval', 'fk_primitive_field', '?');
INSERT INTO UTWildHarvestRecord_lifeStageRemovalLookup (name, label) VALUES ('0', 'All');
INSERT INTO UTWildHarvestRecord_lifeStageRemovalLookup (name, label) VALUES ('1', 'All (adults and juveniles) except eggs, fruits and seeds');
INSERT INTO UTWildHarvestRecord_lifeStageRemovalLookup (name, label) VALUES ('2', 'Adults only');
INSERT INTO UTWildHarvestRecord_lifeStageRemovalLookup (name, label) VALUES ('3', 'Adults (breeding age only)');
INSERT INTO UTWildHarvestRecord_lifeStageRemovalLookup (name, label) VALUES ('4', 'Adults (post breeding age only)');
INSERT INTO UTWildHarvestRecord_lifeStageRemovalLookup (name, label) VALUES ('5', 'Juveniles only');
INSERT INTO UTWildHarvestRecord_lifeStageRemovalLookup (name, label) VALUES ('6', 'Eggs, fruits, seeds only');
INSERT INTO UTWildHarvestRecord_lifeStageRemovalLookup (name, label) VALUES ('7', 'Unknown');
INSERT INTO UTWildHarvestRecord (name, data_type, number_allowed) VALUES ('genderRemoval', 'fk_primitive_field', '?');
INSERT INTO UTWildHarvestRecord_genderRemovalLookup (name, label) VALUES ('0', 'Both sexes (incl. Hermaphrodites)');
INSERT INTO UTWildHarvestRecord_genderRemovalLookup (name, label) VALUES ('1', 'Males only');
INSERT INTO UTWildHarvestRecord_genderRemovalLookup (name, label) VALUES ('2', 'Females only');
INSERT INTO UTWildHarvestRecord_genderRemovalLookup (name, label) VALUES ('3', 'Unknown');
INSERT INTO UTWildHarvestRecord_genderRemovalLookup (name, label) VALUES ('4', 'Not Applicable');
INSERT INTO UTWildHarvestRecord (name, data_type, number_allowed) VALUES ('relativeHarvest', 'fk_primitive_field', '?');
INSERT INTO UTWildHarvestRecord_relativeHarvestLookup (name, label) VALUES ('0', 'Very low (approx 0-9%)');
INSERT INTO UTWildHarvestRecord_relativeHarvestLookup (name, label) VALUES ('1', 'Low to medium (approx 10-49%)');
INSERT INTO UTWildHarvestRecord_relativeHarvestLookup (name, label) VALUES ('2', 'Medium to high (approx 50-89%)');
INSERT INTO UTWildHarvestRecord_relativeHarvestLookup (name, label) VALUES ('3', 'Very high (approx 90-100%)');
INSERT INTO UTWildHarvestRecord_relativeHarvestLookup (name, label) VALUES ('4', 'Unknown');
INSERT INTO UTWildHarvestRecord (name, data_type, number_allowed) VALUES ('harvestLevel', 'float_primitive_field', '?');
INSERT INTO UTWildHarvestRecord (name, data_type, number_allowed) VALUES ('harvestLevelUnits', 'fk_primitive_field', '?');
INSERT INTO UTWildHarvestRecord_harvestLevelUnitsLookup (name, label) VALUES ('0', 'Volume (cubic metres)');
INSERT INTO UTWildHarvestRecord_harvestLevelUnitsLookup (name, label) VALUES ('1', 'Weight (kgs)');
INSERT INTO UTWildHarvestRecord_harvestLevelUnitsLookup (name, label) VALUES ('2', 'Number of individuals');
INSERT INTO UTWildHarvestRecord (name, data_type, number_allowed) VALUES ('documentation', 'text_primitive_field', '?');
INSERT INTO UTWildHarvestRecord (name, data_type, number_allowed) VALUES ('thisConservationBenefits', 'boolean_unknown_primitive_field', '?');
INSERT INTO UTWildHarvestRecord (name, data_type, number_allowed) VALUES ('thisConservationBenefitsText', 'text_primitive_field', '?');
INSERT INTO UTWildHarvestRecord (name, data_type, number_allowed) VALUES ('otherConservationBenefits', 'boolean_unknown_primitive_field', '?');
INSERT INTO UTWildHarvestRecord (name, data_type, number_allowed) VALUES ('otherConservationBenefitsText', 'text_primitive_field', '?');
INSERT INTO UTWildHarvestRecord (name, data_type, number_allowed) VALUES ('habitatConservationBenefits', 'boolean_unknown_primitive_field', '?');
INSERT INTO UTWildHarvestRecord (name, data_type, number_allowed) VALUES ('habitatConservationBenefitsText', 'text_primitive_field', '?');
INSERT INTO UTWildHarvestRecord (name, data_type, number_allowed) VALUES ('UTEndUseRecord', 'field', '*');
INSERT INTO UTEndUseRecord (name, data_type, number_allowed) VALUES ('UTEndUseRecordSubfield', 'field', '*');
INSERT INTO UTEndUseRecordSubfield (name, data_type, number_allowed) VALUES ('endUse', 'fk_primitive_field', '?');
INSERT INTO UTEndUseRecord_endUseLookup (name, label) VALUES ('0', 'Food - human');
INSERT INTO UTEndUseRecord_endUseLookup (name, label) VALUES ('1', 'Food - animal');
INSERT INTO UTEndUseRecord_endUseLookup (name, label) VALUES ('2', 'Medicine - human and veterinary');
INSERT INTO UTEndUseRecord_endUseLookup (name, label) VALUES ('3', 'Poisons');
INSERT INTO UTEndUseRecord_endUseLookup (name, label) VALUES ('4', 'Manufacturing chemicals');  
INSERT INTO UTEndUseRecord_endUseLookup (name, label) VALUES ('5', 'Other chemicals ');
INSERT INTO UTEndUseRecord_endUseLookup (name, label) VALUES ('6', 'Fuels');
INSERT INTO UTEndUseRecord_endUseLookup (name, label) VALUES ('7', 'Fibre');
INSERT INTO UTEndUseRecord_endUseLookup (name, label) VALUES ('8', 'Construction or structural materials');
INSERT INTO UTEndUseRecord_endUseLookup (name, label) VALUES ('9', 'Wearing apparel, accessories');
INSERT INTO UTEndUseRecord_endUseLookup (name, label) VALUES ('10', 'Other household goods');
INSERT INTO UTEndUseRecord_endUseLookup (name, label) VALUES ('11', 'Handicrafts, jewellery, etc.');
INSERT INTO UTEndUseRecord_endUseLookup (name, label) VALUES ('12', 'Pets/display animals, horticulture');
INSERT INTO UTEndUseRecord_endUseLookup (name, label) VALUES ('13', 'Research');
INSERT INTO UTEndUseRecord_endUseLookup (name, label) VALUES ('14', 'Sport hunting /specimen collecting');  
INSERT INTO UTEndUseRecord_endUseLookup (name, label) VALUES ('15', 'Establishing ex-situ production *');
INSERT INTO UTEndUseRecord_endUseLookup (name, label) VALUES ('16', 'Other (free text)');
INSERT INTO UTEndUseRecord_endUseLookup (name, label) VALUES ('17', 'Unknown');
INSERT INTO UTEndUseRecordSubfield (name, data_type, number_allowed) VALUES ('endUseOther', 'string_primitive_field', '?');
INSERT INTO UTEndUseRecordSubfield (name, data_type, number_allowed) VALUES ('biologicalPart', 'text_primitive_field', '?');
INSERT INTO UTEndUseRecordSubfield (name, data_type, number_allowed) VALUES ('scale', 'fk_list_primitive_field', '?');
INSERT INTO UTEndUseRecord_scaleLookup (name, label) VALUES ('0', 'Local Subsistence - direct use by harvesters');
INSERT INTO UTEndUseRecord_scaleLookup (name, label) VALUES ('1', 'Local markets/ barter/exchange/ sale');
INSERT INTO UTEndUseRecord_scaleLookup (name, label) VALUES ('2', 'National');
INSERT INTO UTEndUseRecord_scaleLookup (name, label) VALUES ('3', 'International');
INSERT INTO UTEndUseRecordSubfield (name, data_type, number_allowed) VALUES ('driver', 'fk_list_primitive_field', '?');
INSERT INTO UTEndUseRecord_driverLookup (name, label) VALUES ('0', 'Primary');
INSERT INTO UTEndUseRecord_driverLookup (name, label) VALUES ('1', 'Primary (persecution where species is used)');
INSERT INTO UTEndUseRecord_driverLookup (name, label) VALUES ('2', 'Secondary');
INSERT INTO UTEndUseRecord_driverLookup (name, label) VALUES ('3', 'Bycatch (where species is used)');
INSERT INTO UTEndUseRecord_driverLookup (name, label) VALUES ('4', 'Minor');
INSERT INTO UTEndUseRecord_driverLookup (name, label) VALUES ('5', 'Unknown');
INSERT INTO UTEndUseRecordSubfield (name, data_type, number_allowed) VALUES ('driverDetails', 'text_primitive_field', '?');
INSERT INTO UTEndUseRecord_significantRiskLookup (name, label) VALUES ('0', 'Yes');
INSERT INTO UTEndUseRecord_significantRiskLookup (name, label) VALUES ('1', 'Possibly');
INSERT INTO UTEndUseRecord_significantRiskLookup (name, label) VALUES ('2', 'No');
INSERT INTO UTEndUseRecord_significantRiskLookup (name, label) VALUES ('3', 'Unknown');
INSERT INTO UTEndUseRecordSubfield (name, data_type, number_allowed) VALUES ('significantRisk', 'fk_primitive_field', '?');
