package org.iucn.sis.shared.api.models.primitivefields;

import org.iucn.sis.shared.api.models.Field;
import org.iucn.sis.shared.api.models.PrimitiveField;

/**
 * BooleanPrimitiveField generated by hbm2java
 */
public class BooleanPrimitiveField extends PrimitiveField<Boolean> implements
		java.io.Serializable {

	private Boolean value;

	public BooleanPrimitiveField() {
	}

	public BooleanPrimitiveField(String name, Field field) {
		super(name, field);
	}
	
	public BooleanPrimitiveField(String name, Field field, Boolean value) {
		super(name, field);
		this.value = value;
	}

	public Boolean getValue() {
		return this.value;
	}

	@Override
	public String getSimpleName() {
		return PrimitiveFieldFactory.BOOLEAN_PRIMITIVE;
	}
	
	public void setValue(Boolean value) {
		this.value = value;
	}

	public BooleanPrimitiveField deepCopy() {
		BooleanPrimitiveField copy = new BooleanPrimitiveField();
		copyInto(copy);
		return copy;
	}

	public void setRawValue(String value) {
		setValue(Boolean.valueOf(value));
	}
}
