package org.iucn.sis.shared.api.models.primitivefields;

import org.iucn.sis.shared.api.models.Field;
import org.iucn.sis.shared.api.models.PrimitiveField;

/**
 * BooleanRangePrimitiveField generated by hbm2java
 */
public class BooleanRangePrimitiveField extends PrimitiveField<String> implements
		java.io.Serializable {
	
	public static final String YES = "1";
	public static final String NO = "0";
	public static final String UNKNOWN = "U";

	private String value;

	public BooleanRangePrimitiveField() {
	}

	public BooleanRangePrimitiveField(String name, Field field) {
		super(name, field);
	}
	
	public BooleanRangePrimitiveField(String name, Field field, String value) {
		super(name, field);
		this.value = value;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}
	
	@Override
	public String getSimpleName() {
		return PrimitiveFieldType.BOOLEAN_RANGE_PRIMITIVE.getName();
	}
	
	@Override
	public BooleanRangePrimitiveField deepCopy() {
		BooleanRangePrimitiveField ret = new BooleanRangePrimitiveField();
		copyInto(ret);
		return ret;
	}

	@Override
	public void setRawValue(String value) {
		setValue(value);
	}
	
	public static String getDisplayString(String data) {
		String result;
		if (data == null || "".equals(data))
			result = "(Not Specified)";
		else if (data.equals(BooleanRangePrimitiveField.UNKNOWN))
			result = "Unknown";
		else if (data.equals(BooleanRangePrimitiveField.YES))
			result = "Yes";
		else if (data.equals(BooleanRangePrimitiveField.NO))
			result = "No";
		else
			result = "Custom range: " + data;
		
		return result;
	}
}
