package org.iucn.sis.shared.api.models.primitivefields;

import org.iucn.sis.shared.api.models.Field;
import org.iucn.sis.shared.api.models.PrimitiveField;

/**
 * BooleanRangePrimitiveField generated by hbm2java
 */
public class BooleanRangePrimitiveField extends PrimitiveField<String> implements
		java.io.Serializable {

	private String value;

	public BooleanRangePrimitiveField() {
	}

	public BooleanRangePrimitiveField(String name, Field field) {
		super(name, field);
	}
	
	public BooleanRangePrimitiveField(String name, Field field, String value) {
		super(name, field);
		this.value = value;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}
	
	@Override
	public String getSimpleName() {
		return PrimitiveFieldFactory.BOOLEAN_RANGE_PRIMITIVE;
	}
	
	@Override
	public BooleanRangePrimitiveField deepCopy() {
		BooleanRangePrimitiveField ret = new BooleanRangePrimitiveField();
		copyInto(ret);
		return ret;
	}

	@Override
	public void setRawValue(String value) {
		setValue(value);
	}
}
