package org.iucn.sis.shared.api.models.primitivefields;
// default package
// Generated Apr 27, 2010 9:30:39 AM by Hibernate Tools 3.3.0.GA

import java.util.Date;

import org.iucn.sis.shared.api.models.Field;
import org.iucn.sis.shared.api.models.PrimitiveField;

/**
 * DatePrimitiveField generated by hbm2java
 */
public class DatePrimitiveField extends PrimitiveField<Date> implements
		java.io.Serializable {

	private Date value;

	public DatePrimitiveField() {
	}

	public DatePrimitiveField(String name, Field field) {
		super(name, field);
	}
	
	public DatePrimitiveField(String name, Field field, Date value) {
		super(name, field);
		this.value = value;
	}

	public Date getValue() {
		return this.value;
	}

	public void setValue(Date value) {
		this.value = value;
	}

	@Override
	public String getRawValue() {
		return String.valueOf(getValue().getTime());
	}
	
	@Override
	public void setRawValue(String value) {
		if( value.matches("-?\\d+"))
			setValue(new Date(Long.parseLong(value)));
		else
			throw new NumberFormatException("Not a long.");
	}
	
	@Override
	public String getSimpleName() {
		return PrimitiveFieldFactory.DATE_PRIMITIVE;
	}
	
	@Override
	public DatePrimitiveField deepCopy() {
		DatePrimitiveField ret = new DatePrimitiveField();
		copyInto(ret);
		return ret;
	}
}
