package org.iucn.sis.shared.api.models.primitivefields;

import org.iucn.sis.shared.api.models.Field;
import org.iucn.sis.shared.api.models.PrimitiveField;

/**
 * IntegerPrimitiveField generated by hbm2java
 */
public class IntegerPrimitiveField extends PrimitiveField<Integer> implements
		java.io.Serializable {

	private Integer value;

	public IntegerPrimitiveField() {
	}

	public IntegerPrimitiveField(String name, Field field) {
		super(name, field);
	}
	
	public IntegerPrimitiveField(String name, Field field, Integer value) {
		super(name, field);
		this.value = value;
	}

	@Override
	public String getSimpleName() {
		return PrimitiveFieldType.INTEGER_PRIMITIVE.getName();
	}
	
	public Integer getValue() {
		return this.value;
	}

	public void setValue(Integer value) {
		this.value = value;
	}

	@Override
	/**
	 * Performs addition - newValue + current float value.
	 */
	public void appendValue(Integer newValue) {
		setValue(getValue() + newValue);
	}
	
	@Override
	public IntegerPrimitiveField deepCopy() {
		IntegerPrimitiveField ret = new IntegerPrimitiveField();
		copyInto(ret);
		return ret;
	}

	@Override
	public void setRawValue(String value) throws NumberFormatException {
		setValue(Integer.valueOf(value));
	}
}
