package org.iucn.sis.shared.api.models.primitivefields;

import org.iucn.sis.shared.api.models.Field;
import org.iucn.sis.shared.api.models.PrimitiveField;

/**
 * RangePrimitiveField generated by hbm2java
 */
public class RangePrimitiveField extends PrimitiveField<String> implements
		java.io.Serializable {

	private String value;

	public RangePrimitiveField() {
	}
	
	public RangePrimitiveField(String name, Field field) {
		super(name, field);
	}

	public RangePrimitiveField(String name, Field field, String value) {
		super(name, field);
		this.value = value;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Override
	public String getSimpleName() {
		return PrimitiveFieldType.RANGE_PRIMITIVE.getName();
	}
	
	@Override
	public RangePrimitiveField deepCopy() {
		RangePrimitiveField ret = new RangePrimitiveField();
		copyInto(ret);
		return ret;
	}

	@Override
	public void setRawValue(String value) {
		setValue(value);
	}
}
