package org.iucn.sis.shared.api.models.primitivefields;

import org.iucn.sis.shared.api.models.Field;
import org.iucn.sis.shared.api.models.PrimitiveField;

/**
 * StringPrimitiveField generated by hbm2java
 */
public class StringPrimitiveField extends PrimitiveField<String> implements
		java.io.Serializable {

	private String value;

	public StringPrimitiveField() {
	}
	
	public StringPrimitiveField(String name, Field field) {
		super(name, field);
	}

	public StringPrimitiveField(String name, Field field, String value) {
		super(name, field);
		this.value = value;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Override
	public String getSimpleName() {
		return PrimitiveFieldType.STRING_PRIMITIVE.getName();
	}
	
	@Override
	public StringPrimitiveField deepCopy() {
		StringPrimitiveField ret = new StringPrimitiveField();
		copyInto(ret);
		return ret;
	}

	@Override
	public void setRawValue(String value) {
		setValue(value);
	}
}
