package org.iucn.sis.shared.api.models.primitivefields;

import org.iucn.sis.shared.api.models.Field;
import org.iucn.sis.shared.api.models.PrimitiveField;

/**
 * TextPrimitiveField generated by hbm2java
 */
public class TextPrimitiveField extends PrimitiveField<String> implements
		java.io.Serializable {

	private String value;

	public TextPrimitiveField() {
	}
	
	public TextPrimitiveField(String name, Field field) {
		super(name, field);
	}

	public TextPrimitiveField(String name, Field field, String value) {
		super(name, field);
		this.value = value;
	}

	@Override
	public String getSimpleName() {
		return PrimitiveFieldFactory.TEXT_PRIMITIVE;
	}
	
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Override
	public TextPrimitiveField deepCopy() {
		TextPrimitiveField ret = new TextPrimitiveField();
		copyInto(ret);
		return ret;
	}

	@Override
	public void setRawValue(String value) {
		setValue(value);
	}
}
